fileGroups:
  sources:
    - 'src/**/*'
    - 'src-tauri/**/*'
    - 'tauri.conf.json'
    - 'vite.config.js'
    - 'package.json'
    - 'Cargo.toml'
    - 'Cargo.lock'

tasks:
  
  install:
    command: 'npm install --legacy-peer-deps'
    inputs:
      - 'package.json'
    options:
      cache: false

  dev:
    command: 'cargo tauri dev'
    deps: ['install']
    inputs:
      - '@globs(sources)'
    options:
      persistent: true

  build:
    command: 'cargo tauri build'
    deps: ['install']
    inputs:
      - '@globs(sources)'
    outputs:
      - '/target/release'
